name: Upload Images to Amazon EFS
on:
  push:
    paths:
      - 'imagens/**'

jobs:
  upload_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find new images
        id: find_images
        run: |
          echo "::set-output name=images::$(find imagens -type f \( -name '*.jpg' -o -name '*.png' \))"

      - name: Mount Amazon EFS
        run: sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-01585c82713417e99.efs.us-east-1.amazonaws.com:/ /efs

      - name: Copy images to Amazon EFS
        run: |
          for image in ${{ steps.find_images.outputs.images }}; do
            cp $image /mnt/efs
          done
